### PR TITLE
Update setup

### PR DESCRIPTION
**Pull request by RomeshA**
Moves `line_profiler` to an optional dependency because it can be problematic to install on Windows machines (issues compiling on Azure)

### CODE REVIEW

**Comment by RomeshA** [comment]
I'm almost inclined to say that we could just treat 'line_profiler' as a special case and mention it in the readme and error message instead of doing anything special in `setup.py` - it's the only one that actually seems to cause a problem and I imagine >95% of the time someone would hit this issue interactively (since it's profiling after all!) and then they'd just install the dependency and carry on...!

But otherwise I don't really mind how it's handled except to note that it would also need to work via `pip install sciris` so while the implementation here supports `pip install sciris[profiling]` (and `sciris[profiling]` as the dependency listed in `setup.py` in other packages)  I'm not sure whether an `if` statement in `setup.py` would work for that? Do you know if it works?

**Comment by cliffckerr** [comment]
@RomeshA I think this solution should work:
https://hynek.me/articles/conditional-python-dependencies/
Will implement for both `line_profiler` and `colorama` and let you review.

**Comment by cliffckerr** [comment]
@RomeshA Could you let me know if that works for you?

**Comment by RomeshA** [comment]
Tested on Windows and Ubuntu, looks good to me!

**Pull request merged**
