### PR TITLE
Simplify ASD output

### PR DESCRIPTION
**Pull request by cliffckerr**
I think it's useful to allow the syntax `x = sc.asd(x0)` rather than the hard-to-intuit `x = sc.asd(x0)[0]`. I don't think there needs to be consistency in output between `fulloutput=True` and `fulloutput=False` because there's no harm in just leaving it set to `True` if you prefer that syntax.

Another option would be to return a results object, a la `scipy.optimize.minimize()`: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult

Perhaps we should have `fulloutput=True` return an object (or an `objdict`) with attributes `x`, `fval`, `details`, and have `fulloutput=False` return just `x`? I would just make this change except I'm worried about breaking things...

### CODE REVIEW

**Comment by RomeshA** [comment]
I think this PR would be OK - personally though, I think it's one of those tradeoffs where `x = sc.asd(x0)` is easier at the point where you use it, but it's easier in the longer term to work with functions that return predicable output types/shapes. The other thing is, for backwards compatibility it's probably important to have `fulloutput=True` as the default. But that would mean you can't just write `x = sc.asd(x0)`, it's always going to be `x = sc.asd(x0,fulloutput=False)` which, although a bit clearer than `x = sc.asd(x0)[0]`, is also more verbose - so there would probably be just as much typing if using it interactively. Actually,m since `fulloutput=True` doesn't look like it meaningfully increases compute time, I'd be in favour of simplifying by removing that argument entirely and just always returning the details...?

**Comment by cliffckerr** [comment]
@RomeshA Ha, I forgot that `fulloutput=True` was the default! In that case what about returning an equivalent to the `OptimizeResult` object?
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult
It would be nice to _actually_ return an `OptimizeResult` object, but I don't want to introduce a dependency on scipy just for that...

As for backwards compatibility, we could implement a `__getitem__` method for the object such that `res[0] = res.x`?

**Comment by RomeshA** [comment]
Yeah, actually looking https://github.com/scipy/scipy/blob/v1.3.0/scipy/optimize/optimize.py#L76-L131 it's basically just a dictionary, you can even make one with 

```
import scipy.optimize
a = sc.odict()
a['x'] = [1]
a['success'] = True
b=scipy.optimize.OptimizeResult(a)
```

Then it gets the `res[0] = res.x` indexing for free, and anyone really needing full interoperability could just convert it to an `OptimizeResult` when needed e.g. `res = OptimizeResult(sc.asd(x))`

**Comment by cliffckerr** [comment]
@RomeshA OK cool, I'll make it an `objdict` so you can do `a[0]`, `a['x']`, or `a.x`

**Pull request merged**
